version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432




  user_app:
    build:
    context: ./
    dockerfile: dockerfile

  enviornment:
    - DATABASE_URL="postgresql://postgres:mysecretpassword@postgres:5432/postgres
  ports:
    - 3019:3019
  depends_on:
    - postgres 